<?php

namespace Database\Seeders;

use App\Models\Settings;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    public function run()
    {

        $settingss = [
            [
                'code' => 'company.name',
                'name' => 'Nombre de Empresa',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.address',
                'name' => 'Direccion',
                'active' => true,
                'line_height' => 3,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.city',
                'name' => 'Ciudad',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.depart',
                'name' => 'Departamento',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.country',
                'name' => 'Pais',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.phone',
                'name' => 'Telefono',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'number',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.cell',
                'name' => 'Celular',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'number',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.email',
                'name' => 'Correo',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.iva',
                'name' => 'IVA',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'plain_text',
                'content' => 'null',
                'filetypes' => null,
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'company.logo',
                'name' => 'Logo',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'file',
                'content' => 'null',
                'filetypes' => 'image/*',
                'regex' => null,
                'multiple' => false,
                'child_index' => null,
            ],
            [
                'code' => 'home.slider',
                'name' => 'Home Slider',
                'active' => true,
                'line_height' => 1,
                'content_type' => 'file',
                'content' => 'null',
                'filetypes' => 'image/*,video/*',
                'regex' => null,
                'multiple' => true,
                'child_index' => null,
            ],
        ];
        Settings::insert($settingss);
    }
}
